# Generated by Django 2.1.11 on 2019-09-26 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyContract',
            fields=[
                ('id_contract', models.AutoField(db_column='ID_CONTRACT', primary_key=True, serialize=False)),
                ('modality', models.CharField(db_column='MODALITY', max_length=13)),
                ('sap_contract', models.DecimalField(blank=True, db_column='SAP_CONTRACT', decimal_places=0, max_digits=10, null=True)),
                ('type', models.CharField(blank=True, db_column='TYPE', max_length=1, null=True)),
                ('start_supply', models.DateTimeField(db_column='START_SUPPLY')),
                ('end_supply', models.DateTimeField(db_column='END_SUPPLY')),
                ('contract_status', models.CharField(blank=True, db_column='CONTRACT_STATUS', max_length=2, null=True)),
                ('signing_data', models.DateTimeField(db_column='SIGNING_DATA')),
                ('volume_mwm', models.DecimalField(blank=True, db_column='VOLUME__MWM', decimal_places=9, max_digits=18, null=True)),
                ('volume_mwh', models.DecimalField(blank=True, db_column='VOLUME__MWH', decimal_places=9, max_digits=18, null=True)),
                ('contract_name', models.CharField(db_column='CONTRACT_NAME', max_length=30, unique=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
            ],
            options={
                'db_table': 'ENERGY_CONTRACT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnergyProduct',
            fields=[
                ('id_energy_product', models.AutoField(db_column='ID_ENERGY_PRODUCT', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=30)),
            ],
            options={
                'db_table': 'ENERGY_PRODUCT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flexibilization',
            fields=[
                ('id_contract', models.OneToOneField(db_column='ID_CONTRACT', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='flexib_energy_contract', serialize=False, to='energy_contract.EnergyContract')),
                ('flexibility_type', models.CharField(db_column='FLEXIBILITY_TYPE', max_length=30)),
                ('min_flexibility_pu', models.DecimalField(db_column='MIN_FLEXIBILITY_PU', decimal_places=9, max_digits=18)),
                ('max_flexibility_pu', models.DecimalField(db_column='MAX_FLEXIBILITY_PU', decimal_places=9, max_digits=18)),
                ('proinfa_flexibility', models.CharField(db_column='PROINFA_FLEXIBILITY', max_length=1)),
            ],
            options={
                'db_table': 'FLEXIBILIZATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id_contract', models.OneToOneField(db_column='ID_CONTRACT', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='guaran_energy_contract', serialize=False, to='energy_contract.EnergyContract')),
                ('month_hour', models.DecimalField(db_column='MONTH_HOUR', decimal_places=0, max_digits=3)),
                ('guaranteed_value', models.DecimalField(db_column='GUARANTEED_VALUE', decimal_places=9, max_digits=18)),
                ('emission_date', models.DateTimeField(db_column='EMISSION_DATE')),
                ('effective_date', models.DateTimeField(db_column='EFFECTIVE_DATE')),
            ],
            options={
                'db_table': 'GUARANTEE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulation',
            fields=[
                ('id_contract', models.OneToOneField(db_column='ID_CONTRACT', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='modul_energy_contract', serialize=False, to='energy_contract.EnergyContract')),
                ('modulation_type', models.CharField(db_column='MODULATION_TYPE', max_length=30)),
                ('min_modulation_pu', models.DecimalField(db_column='MIN_MODULATION_PU', decimal_places=9, max_digits=18)),
                ('max_modulation_pu', models.DecimalField(db_column='MAX_MODULATION_PU', decimal_places=9, max_digits=18)),
            ],
            options={
                'db_table': 'MODULATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Precification',
            fields=[
                ('id_contract', models.OneToOneField(db_column='ID_CONTRACT', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='precif_energy_contract', serialize=False, to='energy_contract.EnergyContract')),
                ('base_price_mwh', models.DecimalField(db_column='BASE_PRICE_MWH', decimal_places=9, max_digits=18)),
                ('base_price_date', models.DateTimeField(db_column='BASE_PRICE_DATE')),
                ('birthday_date', models.DateTimeField(db_column='BIRTHDAY_DATE')),
                ('price_index', models.CharField(db_column='PRICE_INDEX', max_length=30)),
                ('active_price_mwh', models.DecimalField(blank=True, db_column='ACTIVE_PRICE_MWH', decimal_places=9, max_digits=18, null=True)),
                ('retusd', models.DecimalField(blank=True, db_column='RETUSD', decimal_places=9, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'PRECIFICATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seasonal',
            fields=[
                ('id_contract', models.OneToOneField(db_column='ID_CONTRACT', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='season_energy_contract', serialize=False, to='energy_contract.EnergyContract')),
                ('type_seasonality', models.CharField(db_column='TYPE_SEASONALITY', max_length=30)),
                ('season_min_pu', models.DecimalField(db_column='SEASON_MIN_PU', decimal_places=9, max_digits=18)),
                ('season_max_pu', models.DecimalField(db_column='SEASON_MAX_PU', decimal_places=9, max_digits=18)),
            ],
            options={
                'db_table': 'SEASONAL',
                'managed': False,
            },
        ),
    ]
