# Generated by Django 2.1.11 on 2020-02-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAttachment',
            fields=[
                ('id_attachment', models.AutoField(db_column='ID_ATTACHMENT', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=100, null=True)),
                ('revision', models.CharField(blank=True, db_column='REVISION', max_length=10, null=True)),
                ('comments', models.CharField(blank=True, db_column='COMMENTS', max_length=100, null=True)),
                ('path', models.CharField(blank=True, db_column='PATH', max_length=100, null=True)),
            ],
            options={
                'db_table': 'CONTRACT_ATTACHMENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalVariable',
            fields=[
                ('id_global_variable', models.AutoField(db_column='ID_GLOBAL_VARIABLE', primary_key=True, serialize=False)),
                ('id_variable', models.DecimalField(blank=True, db_column='ID_VARIABLE', decimal_places=0, max_digits=9, null=True)),
                ('id_unity', models.DecimalField(blank=True, db_column='ID_UNITY', decimal_places=0, max_digits=9, null=True)),
                ('id_state', models.DecimalField(blank=True, db_column='ID_STATE', decimal_places=0, max_digits=9, null=True)),
                ('value', models.DecimalField(blank=True, db_column='VALUE', decimal_places=9, max_digits=18, null=True)),
                ('month', models.DecimalField(blank=True, db_column='MONTH', decimal_places=0, max_digits=2, null=True)),
                ('year', models.DecimalField(blank=True, db_column='YEAR', decimal_places=0, max_digits=4, null=True)),
                ('marketing_flag', models.CharField(blank=True, db_column='MARKETING_FLAG', max_length=1, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
            ],
            options={
                'db_table': 'GLOBAL_VARIABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id_variable', models.AutoField(db_column='ID_VARIABLE', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=40, null=True)),
            ],
            options={
                'db_table': 'Variable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VariableType',
            fields=[
                ('id_variable', models.AutoField(db_column='ID_VARIABLE', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Variable_Type',
                'managed': False,
            },
        ),
    ]
