# Generated by Django 2.1.11 on 2019-09-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_profile', models.AutoField(db_column='ID_PROFILE', primary_key=True, serialize=False)),
                ('name_profile', models.CharField(db_column='NAME_PROFILE', max_length=40)),
                ('alpha', models.CharField(db_column='ALPHA', max_length=1)),
                ('status', models.CharField(db_column='STATUS', max_length=1)),
            ],
            options={
                'db_table': 'PROFILE',
                'managed': False,
            },
        ),
    ]
