# Generated by Django 2.1.11 on 2020-02-11 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountantArea',
            fields=[
                ('id_accountant', models.AutoField(db_column='ID_ACCOUNTANT', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=40, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
            ],
            options={
                'db_table': 'ACCOUNTANT_AREA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id_address', models.AutoField(db_column='ID_ADDRESS', primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, db_column='STREET', max_length=100, null=True)),
                ('number', models.DecimalField(blank=True, db_column='NUMBER', decimal_places=0, max_digits=9, null=True)),
                ('zip_code', models.CharField(blank=True, db_column='ZIP_CODE', max_length=40, null=True)),
                ('complement', models.CharField(blank=True, db_column='COMPLEMENT', max_length=30, null=True)),
            ],
            options={
                'db_table': 'ADDRESS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id_agents', models.AutoField(db_column='ID_AGENTS', primary_key=True, serialize=False)),
                ('vale_name_agent', models.CharField(db_column='VALE_NAME_AGENT', max_length=40)),
                ('status', models.CharField(db_column='STATUS', max_length=1)),
            ],
            options={
                'db_table': 'AGENTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetItems',
            fields=[
                ('id_asset_items', models.AutoField(db_column='ID_ASSET_ITEMS', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
            ],
            options={
                'db_table': 'ASSET_ITEMS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id_assets', models.AutoField(db_column='ID_ASSETS', primary_key=True, serialize=False)),
                ('show_balance', models.CharField(db_column='SHOW_BALANCE', max_length=30)),
                ('status', models.CharField(db_column='STATUS', max_length=1)),
            ],
            options={
                'db_table': 'ASSETS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetsComposition',
            fields=[
                ('id_assets_composition', models.AutoField(db_column='ID_ASSETS_COMPOSITION', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
            ],
            options={
                'db_table': 'ASSETS_COMPOSITION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id_business', models.AutoField(db_column='ID_BUSINESS', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=40, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
            ],
            options={
                'db_table': 'BUSINESS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CceeDescription',
            fields=[
                ('id_ccee', models.AutoField(db_column='ID_CCEE', primary_key=True, serialize=False)),
                ('code_ccee', models.CharField(db_column='CODE_CCEE', max_length=40)),
                ('type', models.CharField(db_column='TYPE', max_length=40)),
                ('name_ccee', models.CharField(blank=True, db_column='NAME_CCEE', max_length=30, null=True)),
                ('status', models.CharField(db_column='STATUS', max_length=1)),
            ],
            options={
                'db_table': 'CCEE_DESCRIPTION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_city', models.AutoField(db_column='ID_CITY', primary_key=True, serialize=False)),
                ('city_name', models.CharField(blank=True, db_column='CITY_NAME', max_length=40, null=True)),
                ('initials', models.CharField(blank=True, db_column='INITIALS', max_length=40, null=True)),
            ],
            options={
                'db_table': 'CITY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.AutoField(db_column='ID_COMPANY', primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_column='COMPANY_NAME', max_length=100)),
                ('registered_number', models.CharField(db_column='REGISTERED_NUMBER', max_length=12)),
                ('type', models.CharField(db_column='TYPE', max_length=5)),
                ('state_number', models.CharField(db_column='STATE_NUMBER', max_length=18)),
                ('nationality', models.CharField(db_column='NATIONALITY', max_length=3)),
                ('id_sap', models.CharField(db_column='ID_SAP', max_length=18, unique=True)),
                ('characteristics', models.CharField(db_column='CHARACTERISTICS', max_length=30)),
                ('create_date', models.DateTimeField(blank=True, db_column='CREATE_DATE', null=True)),
                ('status', models.CharField(db_column='STATUS', max_length=1)),
            ],
            options={
                'db_table': 'COMPANY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.AutoField(db_column='ID_COUNTRY', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=30)),
                ('initials', models.CharField(blank=True, db_column='INITIALS', max_length=4, null=True)),
            ],
            options={
                'db_table': 'COUNTRY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirectorBoard',
            fields=[
                ('id_director', models.AutoField(db_column='ID_DIRECTOR', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=40, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
            ],
            options={
                'db_table': 'DIRECTOR_BOARD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnergyComposition',
            fields=[
                ('id_energy_composition', models.AutoField(db_column='ID_ENERGY_COMPOSITION', primary_key=True, serialize=False)),
                ('composition_name', models.CharField(db_column='COMPOSITION_NAME', max_length=30, unique=True)),
                ('cost_center', models.CharField(blank=True, db_column='COST_CENTER', max_length=30, null=True)),
                ('profit_center', models.CharField(blank=True, db_column='PROFIT_CENTER', max_length=30, null=True)),
                ('kpi_formulae', models.TextField(blank=True, db_column='KPI_FORMULAE', null=True)),
                ('save_date', models.DateTimeField(blank=True, db_column='SAVE_DATE', null=True)),
                ('composition_loss', models.DecimalField(blank=True, db_column='COMPOSITION_LOSS', decimal_places=9, max_digits=18, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=100, null=True)),
            ],
            options={
                'db_table': 'ENERGY_COMPOSITION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GaugeData',
            fields=[
                ('id_gauge_data', models.AutoField(db_column='ID_GAUGE_DATA', primary_key=True, serialize=False)),
                ('utc_creation', models.DateTimeField(blank=True, db_column='UTC_CREATION', null=True)),
                ('utc_gauge', models.DateTimeField(blank=True, db_column='UTC_GAUGE', null=True)),
                ('value', models.DecimalField(blank=True, db_column='VALUE', decimal_places=9, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'GAUGE_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GaugePoint',
            fields=[
                ('id_gauge', models.AutoField(db_column='ID_GAUGE', primary_key=True, serialize=False)),
                ('participation_sepp', models.CharField(blank=True, db_column='PARTICIPATION_SEPP', max_length=1, null=True)),
                ('gauge_type', models.CharField(blank=True, db_column='GAUGE_TYPE', max_length=30, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
            ],
            options={
                'db_table': 'GAUGE_POINT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImportSource',
            fields=[
                ('id_import_source', models.AutoField(db_column='ID_IMPORT_SOURCE', primary_key=True, serialize=False)),
                ('import_type', models.CharField(db_column='IMPORT_TYPE', max_length=30)),
                ('status', models.CharField(db_column='STATUS', max_length=1)),
            ],
            options={
                'db_table': 'IMPORT_SOURCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(db_column='ID_LOG', primary_key=True, serialize=False)),
                ('field_pk', models.DecimalField(db_column='FIELD_PK', decimal_places=0, max_digits=9, null=True)),
                ('table_name', models.CharField(blank=True, db_column='TABLE_NAME', max_length=30, null=True)),
                ('action_type', models.CharField(blank=True, db_column='ACTION_TYPE', max_length=30, null=True)),
                ('old_value', models.TextField(blank=True, db_column='OLD_VALUE', null=True)),
                ('new_value', models.TextField(blank=True, db_column='NEW_VALUE', null=True)),
                ('observation', models.TextField(blank=True, db_column='OBSERVATION', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
                ('user', models.TextField(blank=True, db_column='USER', null=True)),
            ],
            options={
                'db_table': 'LOG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id_measurements', models.AutoField(db_column='ID_MEASUREMENTS', primary_key=True, serialize=False)),
                ('measurement_name', models.CharField(blank=True, db_column='MEASUREMENT_NAME', max_length=40, null=True)),
                ('unity', models.CharField(blank=True, db_column='UNITY', max_length=8, null=True)),
                ('frequency', models.CharField(db_column='FREQUENCY', max_length=30)),
            ],
            options={
                'db_table': 'MEASUREMENTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeteringReportData',
            fields=[
                ('id', models.AutoField(db_column='ID_METERING_REPORT_DATA', primary_key=True, serialize=False)),
                ('ccee_code', models.CharField(max_length=40, null=True)),
                ('gauge_tag', models.CharField(max_length=50, null=True)),
                ('associated_company', models.CharField(max_length=100)),
                ('director_board', models.CharField(max_length=40, null=True)),
                ('business', models.CharField(max_length=40, null=True)),
                ('data_source', models.CharField(max_length=4, null=True)),
                ('loss_type', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'METERING_REPORT_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeteringReportValue',
            fields=[
                ('id', models.AutoField(db_column='ID_METERING_VALUE', primary_key=True, serialize=False)),
                ('off_peak_consumption_value', models.DecimalField(decimal_places=9, max_digits=18, null=True)),
                ('on_peak_consumption_value', models.DecimalField(decimal_places=9, max_digits=18, null=True)),
                ('ccee_consumption_value', models.DecimalField(decimal_places=9, max_digits=18, null=True)),
                ('ccee_metering_days', models.DecimalField(decimal_places=9, max_digits=18)),
                ('vale_consumption_value', models.DecimalField(decimal_places=9, max_digits=18, null=True)),
                ('vale_metering_days', models.DecimalField(decimal_places=9, max_digits=18)),
                ('loss', models.DecimalField(decimal_places=9, max_digits=18, null=True)),
                ('total_consumption_loss', models.DecimalField(decimal_places=9, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'METERING_REPORT_VALUE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(db_column='ID_PRODUCT', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=30, null=True)),
            ],
            options={
                'db_table': 'PRODUCT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_profile', models.AutoField(db_column='ID_PROFILE', primary_key=True, serialize=False)),
                ('name_profile', models.CharField(db_column='NAME_PROFILE', max_length=40)),
                ('alpha', models.CharField(db_column='ALPHA', max_length=1)),
                ('status', models.CharField(db_column='STATUS', max_length=1)),
            ],
            options={
                'db_table': 'PROFILE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(db_column='ID_REPORT', primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(db_column='CREATION_DATE', default=datetime.datetime.now)),
                ('report_name', models.CharField(db_column='REPORT_NAME', max_length=50, unique=True)),
                ('status', models.CharField(db_column='STATUS', default=None, max_length=1)),
                ('month', models.CharField(db_column='MONTH', default=None, max_length=2)),
                ('year', models.CharField(db_column='YEAR', default=None, max_length=4)),
                ('limit_value', models.DecimalField(db_column='LIMIT_VALUE', decimal_places=9, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'REPORT_TABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(db_column='ID_REPORT_TYPE', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='REPORT_NAME', max_length=50)),
                ('initials', models.CharField(db_column='REPORT_INITIALS', max_length=3)),
            ],
            options={
                'db_table': 'REPORT_TYPE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id_segment', models.AutoField(db_column='ID_SEGMENT', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=30, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
            ],
            options={
                'db_table': 'SEGMENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SourcePme',
            fields=[
                ('id_source', models.AutoField(db_column='ID_SOURCE', primary_key=True, serialize=False)),
                ('display_name', models.CharField(db_column='DISPLAY_NAME', max_length=50)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=50)),
            ],
            options={
                'db_table': 'SOURCE_PME',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id_state', models.AutoField(db_column='ID_STATE', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=100, null=True)),
                ('initials', models.CharField(blank=True, db_column='INITIALS', max_length=4, null=True)),
            ],
            options={
                'db_table': 'STATE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submarket',
            fields=[
                ('id_submarket', models.AutoField(db_column='ID_SUBMARKET', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=5)),
                ('status', models.CharField(db_column='STATUS', max_length=1)),
            ],
            options={
                'db_table': 'SUBMARKET',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeAddress',
            fields=[
                ('id_type', models.AutoField(db_column='ID_TYPE', primary_key=True, serialize=False)),
                ('public_place_type', models.CharField(blank=True, db_column='PUBLIC_PLACE_TYPE', max_length=40, null=True)),
            ],
            options={
                'db_table': 'TYPE_ADDRESS',
                'managed': False,
            },
        ),
    ]
