# Generated by Django 2.1.11 on 2020-04-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalGrouping',
            fields=[
                ('id_electrical_grouping', models.AutoField(db_column='ID_ELECTRICAL_GROUPING', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=50)),
                ('status', models.CharField(db_column='STATUS', max_length=1)),
            ],
            options={
                'db_table': 'ELECTRICAL_GROUPING',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationalType',
            fields=[
                ('id_organizational_type', models.AutoField(db_column='ID_ORGANIZATIONAL_TYPE', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=50)),
                ('table_reference', models.CharField(blank=True, db_column='TABLE_REFERENCE', max_length=128, null=True)),
            ],
            options={
                'db_table': 'ORGANIZATIONAL_TYPE',
                'managed': False,
            },
        ),
    ]
