# Generated by Django 2.1.11 on 2020-02-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferContractPriority',
            fields=[
                ('id_transfer', models.AutoField(db_column='ID_TRANSFER', primary_key=True, serialize=False)),
                ('priority_number', models.DecimalField(blank=True, db_column='PRIORITY_NUMBER', decimal_places=0, max_digits=4, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
            ],
            options={
                'db_table': 'TRANSFER_CONTRACT_PRIORITY',
                'managed': False,
            },
        ),
    ]
