# Generated by Django 2.1.11 on 2019-09-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id_assets', models.AutoField(db_column='ID_ASSETS', primary_key=True, serialize=False)),
                ('show_balance', models.CharField(db_column='SHOW_BALANCE', max_length=30)),
                ('status', models.CharField(db_column='STATUS', max_length=1)),
            ],
            options={
                'db_table': 'ASSETS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submarket',
            fields=[
                ('id_submarket', models.AutoField(db_column='ID_SUBMARKET', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=5)),
                ('status', models.CharField(db_column='STATUS', max_length=1)),
            ],
            options={
                'db_table': 'SUBMARKET',
                'managed': False,
            },
        ),
    ]
