# Generated by Django 2.1.11 on 2020-02-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetItems',
            fields=[
                ('id_asset_items', models.AutoField(db_column='ID_ASSET_ITEMS', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
            ],
            options={
                'db_table': 'ASSET_ITEMS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonalityAssetItem',
            fields=[
                ('id_seasonality_asset_item', models.AutoField(db_column='ID_SEASONALITY_ASSET_ITEM', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'seasonality_asset_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonalityAssetItemCost',
            fields=[
                ('id_seasonality_asset_item_cost', models.AutoField(db_column='ID_SEASONALITY_ASSET_ITEM_COST', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SEASONALITY_ASSET_ITEM_COST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeazonalityAssetItemDepreciation',
            fields=[
                ('seazonality_asset_depreciation', models.AutoField(db_column='SEAZONALITY_ASSET_DEPRECIATION', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SEAZONALITY_ASSET_ITEM_DEPRECIATION',
                'managed': False,
            },
        ),
    ]
