# Generated by Django 2.1.11 on 2020-02-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(db_column='ID_COUNTRY', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=30)),
                ('initials', models.CharField(blank=True, db_column='INITIALS', max_length=4, null=True)),
            ],
            options={
                'db_table': 'COUNTRY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalVariable',
            fields=[
                ('id', models.AutoField(db_column='ID_GLOBAL_VARIABLE', primary_key=True, serialize=False)),
                ('value', models.DecimalField(blank=True, db_column='VALUE', decimal_places=9, max_digits=18, null=True)),
                ('month', models.DecimalField(blank=True, db_column='MONTH', decimal_places=0, max_digits=2, null=True)),
                ('year', models.DecimalField(blank=True, db_column='YEAR', decimal_places=0, max_digits=4, null=True)),
                ('marketing', models.BooleanField(db_column='MARKETING_FLAG', default=False)),
                ('status', models.BooleanField(db_column='STATUS', default=True)),
            ],
            options={
                'db_table': 'GLOBAL_VARIABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(db_column='ID_LOG', primary_key=True, serialize=False)),
                ('field_pk', models.DecimalField(db_column='FIELD_PK', decimal_places=0, max_digits=9, null=True)),
                ('table_name', models.CharField(blank=True, db_column='TABLE_NAME', max_length=30, null=True)),
                ('action_type', models.CharField(blank=True, db_column='ACTION_TYPE', max_length=30, null=True)),
                ('old_value', models.TextField(blank=True, db_column='OLD_VALUE', null=True)),
                ('new_value', models.TextField(blank=True, db_column='NEW_VALUE', null=True)),
                ('observation', models.TextField(blank=True, db_column='OBSERVATION', null=True)),
                ('date', models.DateTimeField(auto_now_add=True, db_column='DATE', null=True)),
                ('user', models.TextField(blank=True, db_column='USER', null=True)),
            ],
            options={
                'db_table': 'LOG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(db_column='ID_STATE', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('initials', models.CharField(blank=True, db_column='INITIALS', max_length=4, null=True)),
            ],
            options={
                'db_table': 'STATE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('id', models.AutoField(db_column='ID_UNITY', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=30)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=100)),
            ],
            options={
                'db_table': 'UNITY_TABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(db_column='ID_VARIABLE', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=40)),
            ],
            options={
                'db_table': 'VARIABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VariableType',
            fields=[
                ('id', models.AutoField(db_column='ID_VARIABLE', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=30)),
            ],
            options={
                'db_table': 'VARIABLE_TYPE',
                'managed': False,
            },
        ),
    ]
