DROP TABLE [dbo].[CCT]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CCT](
	[ID_CCT] [numeric](9, 0) IDENTITY(1,1) NOT NULL,
	[ID_USAGE_CONTRACT] [numeric](9, 0) NOT NULL,
	[BEGIN_DATE] [date] NOT NULL,
	[END_DATE] [date] NOT NULL,
	[CONTRACT_VALUE] [numeric](18, 2) NOT NULL,
	[CCT_NUMBER] [numeric](20, 0) NULL,
	[LENGTH] [numeric](18, 2) NULL,
	[DESTINATION] [varchar](512) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CCT] ADD  CONSTRAINT [PK_CCT] PRIMARY KEY CLUSTERED 
(
	[ID_CCT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ENERGY_TRANSMITTER_CCT_FK] ON [dbo].[CCT]
(
	[ID_USAGE_CONTRACT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CCT]  WITH CHECK ADD  CONSTRAINT [CCT_FK_ID_USAGE_CONTRACT_38dcaefa_FK_ENERGY_TRASMITTER_ID_USAGE_CONTRACT] FOREIGN KEY([ID_USAGE_CONTRACT])
REFERENCES [dbo].[ENERGY_TRANSMITTER] ([ID_USAGE_CONTRACT])
GO
ALTER TABLE [dbo].[CCT] CHECK CONSTRAINT [CCT_FK_ID_USAGE_CONTRACT_38dcaefa_FK_ENERGY_TRASMITTER_ID_USAGE_CONTRACT]
GO

