DROP TABLE [dbo].[CONTRACT_CYCLES]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTRACT_CYCLES](
	[ID_CONTRACT_CYCLES] [numeric](9, 0) IDENTITY(1,1) NOT NULL,
	[ID_USAGE_CONTRACT] [numeric](9, 0) NOT NULL,
	[BEGIN_DATE] [date] NOT NULL,
	[END_DATE] [date] NOT NULL,
	[PEAK_MUST] [numeric](18, 2) NULL,
	[OFF_PEAK_MUST] [numeric](18, 2) NULL,
	[PEAK_TAX] [numeric](18, 2) NULL,
	[OFF_PEAK_TAX] [numeric](18, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTRACT_CYCLES] ADD  CONSTRAINT [PK_CONTRACT_CYCLES] PRIMARY KEY CLUSTERED 
(
	[ID_CONTRACT_CYCLES] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FK_ENERGY_TRANSMITTER_CYCLES_FK] ON [dbo].[CONTRACT_CYCLES]
(
	[ID_USAGE_CONTRACT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTRACT_CYCLES]  WITH CHECK ADD  CONSTRAINT [CONTRACT_CYCLES_FK_ID_USAGE_CONTRACT_38dcaefa_FK_ENERGY_TRASMITTER_ID_USAGE_CONTRACT] FOREIGN KEY([ID_USAGE_CONTRACT])
REFERENCES [dbo].[ENERGY_TRANSMITTER] ([ID_USAGE_CONTRACT])
GO
ALTER TABLE [dbo].[CONTRACT_CYCLES] CHECK CONSTRAINT [CONTRACT_CYCLES_FK_ID_USAGE_CONTRACT_38dcaefa_FK_ENERGY_TRASMITTER_ID_USAGE_CONTRACT]
GO
