DROP TABLE [dbo].[ENERGY_TRANSMITTER]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ENERGY_TRANSMITTER](
	[ID_USAGE_CONTRACT] [numeric](9, 0) NOT NULL,
    [ONS_CODE] [varchar](20) NOT NULL,
	[ANEEL_RESOLUTION] [nvarchar](30) NULL,
	[ANEEL_PUBLICATION] [date] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ENERGY_TRANSMITTER] ADD  CONSTRAINT [PK_ENERGY_TRANSMITTER] PRIMARY KEY CLUSTERED 
(
	[ID_USAGE_CONTRACT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FK_USAGE_CONTRACT_ENERGY_FK] ON [dbo].[ENERGY_TRANSMITTER]
(
	[ID_USAGE_CONTRACT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ENERGY_TRANSMITTER]  WITH CHECK ADD  CONSTRAINT [ENERGY_TRANSMITTER_ID_USAGE_CONTRACT_fk_USAGE_CONTRACT_ID_USAGE_CONTRACT] FOREIGN KEY([ID_USAGE_CONTRACT])
REFERENCES [dbo].[USAGE_CONTRACT] ([ID_USAGE_CONTRACT])
GO
ALTER TABLE [dbo].[ENERGY_TRANSMITTER] CHECK CONSTRAINT [ENERGY_TRANSMITTER_ID_USAGE_CONTRACT_fk_USAGE_CONTRACT_ID_USAGE_CONTRACT]
GO

