DROP TABLE [dbo].[TAX_MODALITY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAX_MODALITY](
	[ID_TAX_MODALITY] [numeric](9, 0) IDENTITY(1,1) NOT NULL,
    [ID_USAGE_CONTRACT] [numeric](9, 0) NOT NULL,
	[BEGIN_DATE] [date] NOT NULL,
	[END_DATE] [date] NOT NULL,
	[PEAK_MUSD] [numeric](18, 2) NULL,
	[OFF_PEAK_MUSD] [numeric](18, 2) NULL,
	[PEAK_TAX] [numeric](18, 2) NULL,
	[OFF_PEAK_TAX] [numeric](18, 2) NULL,
	[UNIQUE_MUSD] [numeric](18, 2) NULL,
	[UNIQUE_TAX] [numeric](18, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAX_MODALITY] ADD  CONSTRAINT [PK_TAX_MODALITY] PRIMARY KEY CLUSTERED 
(
	[ID_TAX_MODALITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FK_VIGENCIA_FK_VIGENC_ENERGY_D_FK] ON [dbo].[TAX_MODALITY]
(
	[ID_USAGE_CONTRACT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAX_MODALITY]  WITH CHECK ADD  CONSTRAINT [TAX_MODALITY_ID_USAGE_CONTRACT_38dcaefa_fk_ENERGY_DISTRIBUTOR_ID_USAGE_CONTRACT] FOREIGN KEY([ID_USAGE_CONTRACT])
REFERENCES [dbo].[ENERGY_DISTRIBUTOR] ([ID_USAGE_CONTRACT])
GO
ALTER TABLE [dbo].[TAX_MODALITY] CHECK CONSTRAINT [TAX_MODALITY_ID_USAGE_CONTRACT_38dcaefa_fk_ENERGY_DISTRIBUTOR_ID_USAGE_CONTRACT]
GO
