# Generated by Django 2.1.11 on 2020-02-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CliqContract',
            fields=[
                ('id_contract_cliq', models.AutoField(db_column='ID_CONTRACT_CLIQ', primary_key=True, serialize=False)),
                ('ccee_type_contract', models.CharField(blank=True, db_column='CCEE_TYPE_CONTRACT', max_length=5, null=True)),
                ('transaction_type', models.CharField(db_column='TRANSACTION_TYPE', max_length=30)),
                ('flexibility', models.CharField(blank=True, db_column='FLEXIBILITY', max_length=12, null=True)),
                ('mwm_volume', models.DecimalField(db_column='MWM_VOLUME', decimal_places=9, max_digits=18)),
                ('contractual_loss', models.DecimalField(blank=True, db_column='CONTRACTUAL_LOSS', decimal_places=9, max_digits=18, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
            ],
            options={
                'db_table': 'CLIQ_CONTRACT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonalityCliq',
            fields=[
                ('id_seasonality_cliq', models.AutoField(db_column='ID_SEASONALITY_CLIQ', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SEASONALITY_CLIQ',
                'managed': False,
            },
        ),
    ]
