# Generated by Django 2.1.11 on 2020-04-08 21:16

import contract_dispatch.models
from django.db import migrations, models
import enumchoicefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CliqContractCurrentStatus',
            fields=[
                ('id_cliq_contract_current_status', models.AutoField(db_column='ID_CLIQ_CONTRACT_CURRENT_STATUS', primary_key=True, serialize=False)),
                ('status', enumchoicefield.fields.EnumChoiceField(db_column='CONTRACT_STATUS', enum_class=contract_dispatch.models.CliqContractStatus, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
            ],
            options={
                'db_table': 'CLIQ_CONTRACT_CURRENT_STATUS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractDispatch',
            fields=[
                ('id', models.AutoField(db_column='ID_CONTRACT_DISPATCH', primary_key=True, serialize=False)),
                ('dispatch_date', models.DateTimeField(db_column='DISPATCH_DATE')),
                ('dispatch_username', models.CharField(db_column='DISPATCH_USERNAME', max_length=50)),
                ('supply_date', models.DateTimeField(db_column='SUPPLY_DATE')),
            ],
            options={
                'db_table': 'CONTRACT_DISPATCH',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractDispatchCliqContract',
            fields=[
                ('id_contract_dispatch_cliq_contract', models.AutoField(db_column='ID_CONTRACT_DISPATCH_CLIQ_CONTRACT', primary_key=True, serialize=False)),
                ('contract_status_on_dispatch', enumchoicefield.fields.EnumChoiceField(db_column='CONTRACT_STATUS', enum_class=contract_dispatch.models.CliqContractStatus, max_length=50)),
            ],
            options={
                'db_table': 'CONTRACT_DISPATCH_CLIQ_CONTRACT',
                'managed': False,
            },
        ),
    ]
