# Generated by Django 2.1.11 on 2020-02-11 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CceeDescription',
            fields=[
                ('id_ccee', models.AutoField(db_column='ID_CCEE', primary_key=True, serialize=False)),
                ('code_ccee', models.CharField(db_column='CODE_CCEE', max_length=40)),
                ('type', models.CharField(db_column='TYPE', max_length=40)),
                ('name_ccee', models.CharField(blank=True, db_column='NAME_CCEE', max_length=30, null=True)),
                ('status', models.CharField(db_column='STATUS', max_length=1)),
            ],
            options={
                'db_table': 'CCEE_DESCRIPTION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.AutoField(db_column='ID_COMPANY', primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_column='COMPANY_NAME', max_length=100)),
                ('registered_number', models.CharField(db_column='REGISTERED_NUMBER', max_length=12)),
                ('type', models.CharField(db_column='TYPE', max_length=5)),
                ('state_number', models.CharField(db_column='STATE_NUMBER', max_length=18)),
                ('nationality', models.CharField(db_column='NATIONALITY', max_length=3)),
                ('id_sap', models.CharField(db_column='ID_SAP', max_length=18, unique=True)),
                ('characteristics', models.CharField(db_column='CHARACTERISTICS', max_length=30)),
                ('create_date', models.DateTimeField(blank=True, db_column='CREATE_DATE', null=True)),
                ('status', models.CharField(db_column='STATUS', max_length=1)),
            ],
            options={
                'db_table': 'COMPANY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyReference',
            fields=[
                ('id', models.AutoField(db_column='ID_REFERENCE', primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(db_column='TRANSACTION_TYPE', max_length=8)),
                ('index_name', models.CharField(db_column='INDEX_NAME', max_length=50)),
                ('creation_date', models.DateTimeField(db_column='CREATION_DATE')),
                ('month', models.DecimalField(db_column='MONTH', decimal_places=0, max_digits=2)),
                ('year', models.DecimalField(db_column='YEAR', decimal_places=0, max_digits=4)),
                ('sap_document_number', models.DecimalField(db_column='SAP_DOCUMENT_NUMBER', decimal_places=0, max_digits=10, null=True)),
                ('status', models.CharField(db_column='STATUS', max_length=1)),
            ],
            options={
                'db_table': 'COMPANY_REFERENCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(db_column='ID_COST_CENTER', primary_key=True, serialize=False)),
                ('statistic_index', models.DecimalField(db_column='ESTATISTIC_INDEX', decimal_places=0, max_digits=9)),
                ('status', models.CharField(db_column='STATUS', max_length=1, null=True)),
                ('cost_index', models.DecimalField(db_column='COST_INDEX', decimal_places=0, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'COST_CENTER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnergyComposition',
            fields=[
                ('id_energy_composition', models.AutoField(db_column='ID_ENERGY_COMPOSITION', primary_key=True, serialize=False)),
                ('composition_name', models.CharField(db_column='COMPOSITION_NAME', max_length=30, unique=True)),
                ('profit_center', models.CharField(blank=True, db_column='PROFIT_CENTER', max_length=30, null=True)),
                ('kpi_formulae', models.TextField(blank=True, db_column='KPI_FORMULAE', null=True)),
                ('save_date', models.DateTimeField(blank=True, db_column='SAVE_DATE', null=True)),
                ('composition_loss', models.DecimalField(blank=True, db_column='COMPOSITION_LOSS', decimal_places=9, max_digits=18, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=100, null=True)),
            ],
            options={
                'db_table': 'ENERGY_COMPOSITION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GaugeData',
            fields=[
                ('id_gauge_data', models.AutoField(db_column='ID_GAUGE_DATA', primary_key=True, serialize=False)),
                ('utc_creation', models.DateTimeField(blank=True, db_column='UTC_CREATION', null=True)),
                ('utc_gauge', models.DateTimeField(blank=True, db_column='UTC_GAUGE', null=True)),
                ('value', models.DecimalField(blank=True, db_column='VALUE', decimal_places=9, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'GAUGE_DATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GaugePoint',
            fields=[
                ('id_gauge', models.AutoField(db_column='ID_GAUGE', primary_key=True, serialize=False)),
                ('connection_point', models.CharField(blank=True, db_column='CONNECTION_POINT', max_length=30, null=True)),
                ('participation_sepp', models.CharField(blank=True, db_column='PARTICIPATION_SEPP', max_length=1, null=True)),
                ('gauge_type', models.CharField(blank=True, db_column='GAUGE_TYPE', max_length=30, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
                ('meter_type', models.CharField(blank=True, db_column='METER_TYPE', max_length=30, null=True)),
                ('peak_time_begin', models.TimeField(blank=True, db_column='PEAK_TIME_BEGIN', null=True)),
                ('peak_time_end', models.TimeField(blank=True, db_column='PEAK_TIME_END', null=True)),
            ],
            options={
                'db_table': 'GAUGE_POINT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalVariable',
            fields=[
                ('id', models.AutoField(db_column='ID_GLOBAL_VARIABLE', primary_key=True, serialize=False)),
                ('value', models.DecimalField(blank=True, db_column='VALUE', decimal_places=9, max_digits=18, null=True)),
                ('month', models.DecimalField(blank=True, db_column='MONTH', decimal_places=0, max_digits=2, null=True)),
                ('year', models.DecimalField(blank=True, db_column='YEAR', decimal_places=0, max_digits=4, null=True)),
                ('marketing', models.BooleanField(db_column='MARKETING_FLAG', default=False)),
                ('status', models.BooleanField(db_column='STATUS', default=True)),
            ],
            options={
                'db_table': 'GLOBAL_VARIABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImportSource',
            fields=[
                ('id', models.AutoField(db_column='ID_IMPORT_SOURCE', primary_key=True, serialize=False)),
                ('import_type', models.CharField(db_column='IMPORT_TYPE', max_length=30)),
                ('status', models.CharField(db_column='STATUS', max_length=1)),
            ],
            options={
                'db_table': 'IMPORT_SOURCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KSB1',
            fields=[
                ('id', models.AutoField(db_column='ID_KSB1', primary_key=True, serialize=False)),
                ('cost_center', models.CharField(db_column='COST_CENTER', max_length=30)),
                ('cost_element_description', models.CharField(db_column='COST_ELEMENT_DESCRIPTION', max_length=250)),
                ('cost_element', models.CharField(db_column='COST_ELEMENT', max_length=250, null=True)),
                ('time_period', models.DecimalField(db_column='TIME_PERIOD', decimal_places=0, max_digits=8)),
                ('currency_value', models.DecimalField(blank=True, db_column='OBJECTS_CURRENCY_VALUE', decimal_places=9, max_digits=18, null=True)),
                ('utc_creation', models.DateTimeField(db_column='UTC_CREATION')),
                ('incoming_date', models.DateTimeField(db_column='INCOMING_DATE')),
                ('incoming_time', models.TimeField(db_column='INCOMING_TIME')),
                ('release_date', models.DateTimeField(db_column='RELEASE_DATE')),
                ('document_number', models.CharField(db_column='DOCUMENT_NUMBER', max_length=250)),
                ('exercise', models.DecimalField(db_column='EXERCISE', decimal_places=0, max_digits=8)),
                ('company', models.CharField(db_column='COMPANY', max_length=250)),
                ('mr_value', models.DecimalField(db_column='MR_VALUE', decimal_places=8, max_digits=16)),
                ('status', models.CharField(db_column='STATUS', max_length=1)),
            ],
            options={
                'db_table': 'KSB1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id_measurements', models.AutoField(db_column='ID_MEASUREMENTS', primary_key=True, serialize=False)),
                ('measurement_name', models.CharField(blank=True, db_column='MEASUREMENT_NAME', max_length=40, null=True)),
                ('unity', models.CharField(blank=True, db_column='UNITY', max_length=8, null=True)),
                ('frequency', models.CharField(db_column='FREQUENCY', max_length=30)),
            ],
            options={
                'db_table': 'MEASUREMENTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(db_column='ID_REPORT', primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(db_column='CREATION_DATE', default=datetime.datetime.now)),
                ('report_name', models.CharField(db_column='REPORT_NAME', max_length=50, unique=True)),
                ('status', models.CharField(db_column='STATUS', default=None, max_length=1)),
                ('month', models.CharField(db_column='MONTH', default=None, max_length=2)),
                ('year', models.CharField(db_column='YEAR', default=None, max_length=4)),
                ('limit_value', models.DecimalField(db_column='LIMIT_VALUE', decimal_places=9, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'REPORT_TABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(db_column='ID_REPORT_TYPE', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='REPORT_NAME', max_length=50)),
                ('initials', models.CharField(db_column='REPORT_INITIALS', max_length=4)),
            ],
            options={
                'db_table': 'REPORT_TYPE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticalIndex',
            fields=[
                ('id', models.AutoField(db_column='ID_STATISTICAL', primary_key=True, serialize=False)),
                ('value', models.DecimalField(db_column='VALUE', decimal_places=8, max_digits=18)),
                ('unity', models.CharField(db_column='UNITY', max_length=4)),
                ('rate_apportionment', models.DecimalField(db_column='RATE_APPORTIONMENT', decimal_places=8, max_digits=18)),
            ],
            options={
                'db_table': 'STATISTICAL_INDEX',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(db_column='ID_VARIABLE', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=40)),
            ],
            options={
                'db_table': 'VARIABLE',
                'managed': False,
            },
        ),
    ]
