# Generated by Django 2.1.11 on 2020-02-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='typeaddess',
            table='TYPE_ADDRESS',
        ),
    ]
