
fbl3n_list = [
    # Campos obrigatorios
    # ----------------------------------------------------------------
    {'column': 'COMPANY', 'type': 1, 'required': True, 'field': u'Empresa'},
    {'column': 'RELEASE_DATE', 'type': 4, 'required': True, 'field': u'Data de lançamento'},
    {'column': 'INTERNAL_CURRENCY', 'type': 1, 'required': True, 'field': u'Moeda interna'},
    {'column': 'INCOMING_DATE', 'type': 4, 'required': True, 'field': u'Data de entrada'},
    {'column': 'INCOMING_TIME', 'type': 5, 'required': True, 'field': u'Hora de entrada'},
    {'column': 'EXERCISE', 'type': 2, 'required': True, 'field': u'Exercício'},
    {'column': 'ACCOUNTING_PERIOD', 'type': 2, 'required': True, 'field': u'Período contábil'},
    # ----------------------------------------------------------------
    {'column': 'OPEN_START_COMP_SYMBOL', 'type': 1, 'required': False, 'field': u'Open start comp symbol'},
    {'column': 'ACCOUNT', 'type': 1, 'required': False, 'field': u'Conta'},
    {'column': 'CREDIT_DEBIT_CODE', 'type': 1, 'required': False, 'field': u'Código de débito e crédito'},
    {'column': 'DOCUMENT_NUMBER', 'type': 1, 'required': False, 'field': u'Número do documento'},
    {'column': 'PROFIT_CENTER', 'type': 1, 'required': False, 'field': u'Centro de lucro'},
    {'column': 'DOCUMENT_TYPE', 'type': 1, 'required': False, 'field': u'Tipo de documento'},
    {'column': 'DOCUMENT_DATE', 'type': 4, 'required': False, 'field': u'Data do documento'},
    {'column': 'AMOUNT_DOMESTIC_CURRENCY', 'type': 3, 'required': False, 'field': u'Montante em moeda doméstica'},
    {'column': 'AMOUNT_DOCUMENT_CURRENCY', 'type': 3, 'required': False, 'field': u'Montante de moeda do documento'},
    {'column': 'BUSINESS_PARTNER', 'type': 1, 'required': False, 'field': u'Sociedade parceira'},
    {'column': 'DOCUMENT_CURRENCY', 'type': 1, 'required': False, 'field': u'Moeda do documento'},
    {'column': 'TEXT_FIELD', 'type': 1, 'required': False, 'field': u'Texto'},
    {'column': 'REFERENCE', 'type': 1, 'required': False, 'field': u'Referência'},
    {'column': 'USERNAME', 'type': 1, 'required': False, 'field': u'Usuário'},
    {'column': 'AMOUNT_INMI2', 'type': 3, 'required': False, 'field': u'Montante em MI2'},
    {'column': 'INTERNAL_CURRENCY_2', 'type': 1, 'required': False, 'field': u'Moeda interna 2'},
    {'column': 'ACCOUNT_TYPE', 'type': 1, 'required': False, 'field': u'Tipo de conta'},
    {'column': 'INVOICE_REFERENCE', 'type': 1, 'required': False, 'field': u'Fatura de referência'},
    {'column': 'CENTER', 'type': 1, 'required': False, 'field': u'Centro'},
    {'column': 'PAYMENT_REFERENCE', 'type': 1, 'required': False, 'field': u'Referência de pagamento'},
    {'column': 'TYPE_CTA_CONTRAPART', 'type': 1, 'required': False, 'field': u'Tipo de conta de contrapartida'},
    {'column': 'USER_NAME_COMPLET', 'type': 1, 'required': False, 'field': u'Usuário nome completo'},
    {'column': 'OPERATION_REFERENCE', 'type': 1, 'required': False, 'field': u'Operação de referência'},
    {'column': 'DOCUMENT_HEADER_TEXT', 'type': 1, 'required': False, 'field': u'Texto do cabeçalho do documento'},
    {'column': 'TRANSACTION_CODE', 'type': 1, 'required': False, 'field': u'Código da transação'},
    {'column': 'PURCHASING_DOCUMENT', 'type': 1, 'required': False, 'field': u'Documento de compra'},
    {'column': 'MATERIAL', 'type': 1, 'required': False, 'field': u'Material'},
    {'column': 'BASIC_MEASUREMENT_UNIT', 'type': 1, 'required': False, 'field': u'Unidade de medida básica'},
    {'column': 'AMOUNT', 'type': 3, 'required': False, 'field': u'Quantidade'},
    {'column': 'TAX_DOMICILE', 'type': 1, 'required': False, 'field': u'Domicílio fiscal'},
]
