ksb1_list = [
    {'column': 'COST_CENTER', 'type': 1, 'required': True, 'field': u'Centro de custo'},
    {'column': 'COST_ELEMENT_DESCRIPTION', 'type': 1, 'required': True, 'field': u'Descrição da classe de custo'},
    {'column': 'INCOMING_DATE', 'type': 4, 'required': True, 'field': u'Data de entrada'},
    {'column': 'INCOMING_TIME', 'type': 5, 'required': True, 'field': u'Horário de entrada'},
    {'column': 'RELEASE_DATE', 'type': 4, 'required': True, 'field': u'Data de lançamento'},
    {'column': 'DOCUMENT_NUMBER', 'type': 1, 'required': True, 'field': u'Número do documento'},
    {'column': 'TIME_PERIOD', 'type': 2, 'required': True, 'field': u'Período'},
    {'column': 'EXERCISE', 'type': 2, 'required': True, 'field': u'Exercício'},
    {'column': 'COMPANY', 'type': 1, 'required': True, 'field': u'Empresa'},
    {'column': 'MR_VALUE', 'type': 3, 'required': True, 'field': u'Valor/MR'},
    {'column': 'BUSINESS_PARTNER', 'type': 1, 'required': False, 'field': u'Sociedade parceira de negócios'},
    {'column': 'COST_ELEMENT', 'type': 1, 'required': True, 'field': u'Classe de custo'},
    {'column': 'TITLE', 'type': 1, 'required': False, 'field': u'Denominação'},
    {'column': 'ORDER_TEXT', 'type': 1, 'required': False, 'field': u'Texto do pedido'},
    {'column': 'OBJECTS_CURRENCY_VALUE', 'type': 3, 'required': False, 'field': u'Valor/moeda objeto'},
    {'column': 'TOTAL_INCOMING_QUANTITY', 'type': 3, 'required': False, 'field': u'Quantidade total de entrada'},
    {'column': 'USERNAME', 'type': 1, 'required': False, 'field': u'Nome do usuário'},
    {'column': 'PURCHASING_DOCUMENT', 'type': 1, 'required': False, 'field': u'Documento de compras'},
    {'column': 'REFERENCED_DOCUMENT_NUMBER', 'type': 1, 'required': False, 'field': u'Número do doumento de referência'},
    {'column': 'DOCUMENT_TYPE', 'type': 1, 'required': False, 'field': u'Tipo de documento'},
    {'column': 'MATERIAL', 'type': 1, 'required': False, 'field': u'Material'},
    {'column': 'OFFSET_ACCOUNT_DESCRIPTION', 'type': 1, 'required': False, 'field': u'Descrição da conta de contrapartida'},
    {'column': 'PARTNER_OBJECT', 'type': 1, 'required': False, 'field': u'Objeto do parceiro'},
    {'column': 'POSTING_LINE', 'type': 2, 'required': False, 'field': u'Linha de lançamento'},
    {'column': 'VALUE_CATEGORY', 'type': 1, 'required': False, 'field': u'Categoria de valor'},
    {'column': 'DEBIT_OR_CREDIT_INDICATOR', 'type': 1, 'required': False, 'field': u'Código débito/crédito'},
    {'column': 'REFERENCE_DOCUMENT_CATEGORY', 'type': 1, 'required': False, 'field': u'Ctg.doc.referência'},
    {'column': 'EXCHANGE_RATE_CATEGORY', 'type': 1, 'required': False, 'field': u'Ctg.taxa câmbio'},
    {'column': 'DOCUMENT_DATE', 'type': 4, 'required': False, 'field': u'Data do documento'},
    {'column': 'EFFECTIVE_DATE', 'type': 4, 'required': False, 'field': u'Data efetiva'},
    {'column': 'COST_ELEMENT_TITLE', 'type': 1, 'required': False, 'field': u'Denominação da classe de custo'},
    {'column': 'OBJECT_TITLE', 'type': 1, 'required': False, 'field': u'Denominação de objeto'},
    {'column': 'SOURCE_OBJECT_TITLE', 'type': 1, 'required': False, 'field': u'Denominação do objeto de origem'},
    {'column': 'PARTNER_OBJECT_TITLE', 'type': 1, 'required': False, 'field': u'Denominação do objeto parceiro'},
    {'column': 'PARTNER_COMPANY', 'type': 1, 'required': False, 'field': u'Empresa parceira'},
    {'column': 'RECORDING_TIME', 'type': 5, 'required': False, 'field': u'Hora do registro'},
    {'column': 'LEDGER', 'type': 1, 'required': False, 'field': u'Ledger'},
    {'column': 'OPERATIVE_VERSION_ROW', 'type': 2, 'required': False, 'field': u'Linha versão operação'},
    {'column': 'ACC_CURRENCY', 'type': 1, 'required': False, 'field': u'Moeda da ACC'},
    {'column': 'TRANSACTION_CURRENCY', 'type': 1, 'required': False, 'field': u'Moeda da transação'},
    {'column': 'OBJECT_CURRENCY', 'type': 1, 'required': False, 'field': u'Moeda do objeto'},
    {'column': 'REPORT_CURRENCY', 'type': 1, 'required': False, 'field': u'Moeda do relatório'},
    {'column': 'CREATION_TIME', 'type': 3, 'required': False, 'field': u'Momento da criação'},
    {'column': 'PERSONAL_NUMBER', 'type': 2, 'required': False, 'field': u'Número pessoal'},
    {'column': 'OBJECTNAME', 'type': 1, 'required': False, 'field': u'Objeto'},
    {'column': 'SOURCE_OBJECT', 'type': 1, 'required': False, 'field': u'Objeto de origem'},
    {'column': 'TRANSACTION_NAME', 'type': 1, 'required': False, 'field': u'Operação'},
    {'column': 'ORIGINAL_TRANSACTION', 'type': 1, 'required': False, 'field': u'Operação original'},
    {'column': 'REFERENCE_TRANSACTION', 'type': 1, 'required': False, 'field': u'Operação referência'},
    {'column': 'PARTNER_ORDER', 'type': 1, 'required': False, 'field': u'Ordem do parceiro'},
    {'column': 'PARTNER_OBJECT_CLASS', 'type': 1, 'required': False, 'field': u'Parceiro classe do objeto'},
    {'column': 'PERIOD_TO', 'type': 2, 'required': False, 'field': u'Período: a'},
    {'column': 'PERIOD_FROM', 'type': 2, 'required': False, 'field': u'Período: de'},
    {'column': 'SEGMENT', 'type': 1, 'required': False, 'field': u'Segmento'},
    {'column': 'PARTNER_SEGMENT', 'type': 1, 'required': False, 'field': u'Segmento do parceiro'},
    {'column': 'SOURCE_OBJECT_TYPE', 'type': 1, 'required': False, 'field': u'Tipo do objeto de origem'},
    {'column': 'DEBT_TYPE', 'type': 2, 'required': False, 'field': u'Tipo de débito'},
    {'column': 'PARTNER_OBJECT_TYPE_1', 'type': 1, 'required': False, 'field': u'Tipo de objeto do parceiro 1'},
    {'column': 'OBJECT_TYPE_1', 'type': 1, 'required': False, 'field': u'Tipo de objeto'},
    {'column': 'OBJECT_TYPE_2', 'type': 1, 'required': False, 'field': u'Tipo de objeto'},
    {'column': 'PARTNER_OBJECT_TYPE_2', 'type': 1, 'required': False, 'field': u'Tipo de objeto do parceiro 2'},
    {'column': 'TP_SOURCE_OBJECT', 'type': 1, 'required': False, 'field': u'Tipo de objeto de origem'},
    {'column': 'POSTED_UNIT_MEASURE', 'type': 1, 'required': False, 'field': u'Unidade de medida lançada'},
    {'column': 'REFERRED_ORGANIZATIONAL_UNIT', 'type': 1, 'required': False, 'field': u'Unidade organizacional de referência'},
    {'column': 'CURRENCY_VARIABLE_VALUE', 'type': 3, 'required': False, 'field': u'Valor var./moeda relat'},
    {'column': 'MTRANSAC_VARIABLE_VALUE', 'type': 3, 'required': False, 'field': u'Valor var./MTransaç.'},
    {'column': 'MOBJ_VARIABLE_VALUE', 'type': 3, 'required': False, 'field': u'Valor variável/MObj.'},
    {'column': 'TRANSACTION_CURRENCY_VALUE', 'type': 3, 'required': False, 'field': u'Valor/moeda de transação'},
    {'column': 'ACC_CURRENCY_VALUE', 'type': 1, 'required': False, 'field': u'Valor/moeda ACC'},
    {'column': 'VERSION_VALUE', 'type': 1, 'required': False, 'field': u'Versão'},
    {'column': 'ACC_FIXED_CURRENCY_VALUE', 'type': 3, 'required': False, 'field': u'Valor fixo/moeda ACC'},
    {'column': 'TR_FIXED_CURRENCY_VALUE', 'type': 3, 'required': False, 'field': u'Valor fixo/moeda tr.'},
    {'column': 'OBJ_FIXED_CURRENCY_VALUE', 'type': 3, 'required': False, 'field': u'Valor fixo/moeda obj'},
    {'column': 'RELAT_FIXED_CURRENCY_VALUE', 'type': 3, 'required': False, 'field': u'Valor fixo/moeda relativa'},
    {'column': 'ACTIVITY_TYPE', 'type': 1, 'required': False, 'field': u'Tipo de atividade'},
    {'column': 'MEASUREMENT_UNIT', 'type': 1, 'required': False, 'field': u'Unidade de medida'},
    {'column': 'TOTAL_AMOUNT', 'type': 3, 'required': False, 'field': u'Quantidade total'},
    {'column': 'PARTNER_OPERATION', 'type': 1, 'required': False, 'field': u'Operação do parceiro'}
]
