# Generated by Django 2.1.11 on 2020-07-07 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(db_column='ID_NOTIFICATION', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=500)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=1000)),
                ('start_date', models.DateField(db_column='START_DATE')),
                ('notification_rule', models.CharField(blank=True, db_column='NOTIFICATION_RULE', max_length=1000)),
                ('notification_rule_processed', models.CharField(blank=True, db_column='NOTIFICATION_RULE_PROCESSED', max_length=1000, null=True)),
                ('subject', models.CharField(blank=True, db_column='SUBJECT', max_length=255)),
                ('message', models.CharField(blank=True, db_column='MESSAGE', max_length=1000)),
                ('entity', models.CharField(blank=True, db_column='ENTITY', max_length=200)),
                ('notification_username', models.CharField(db_column='NOTIFICATION_USERNAME', max_length=100)),
                ('status', models.BooleanField(db_column='STATUS', default=True)),
            ],
            options={
                'db_table': 'NOTIFICATION',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotificationEventHistory',
            fields=[
                ('id', models.AutoField(db_column='ID_NOTIFICATION_EVENT_HISTORY', primary_key=True, serialize=False)),
                ('notification_entity_pk', models.DecimalField(db_column='NOTIFICATION_ENTITY_PK', decimal_places=0, max_digits=9)),
                ('notification', models.ForeignKey(db_column='ID_NOTIFICATION', on_delete=django.db.models.deletion.CASCADE, to='notifications.Notification')),
            ],
            options={
                'db_table': 'NOTIFICATION_EVENT_HISTORY',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotificationFrequency',
            fields=[
                ('id', models.AutoField(db_column='ID_NOTIFICATION_FREQUENCY', primary_key=True, serialize=False)),
                ('notification_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quartely'), ('SEMIANNUALLY', 'Semiannually'), ('ANNUALLY', 'Annually'), ('ON_EVENT', 'On Event')], db_column='NOTIFICATION_FREQUENCY', max_length=50)),
            ],
            options={
                'db_table': 'NOTIFICATION_FREQUENCY',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotificationTargetEmail',
            fields=[
                ('id', models.AutoField(db_column='ID_NOTIFICATION_TARGET_EMAIL', primary_key=True, serialize=False)),
                ('target_email', models.EmailField(db_column='TARGET_EMAIL', max_length=200)),
                ('notification', models.ForeignKey(db_column='ID_NOTIFICATION', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='notifications.Notification')),
            ],
            options={
                'db_table': 'NOTIFICATION_TARGET_EMAIL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.AutoField(db_column='ID_NOTIFICATION_TYPE', primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('CREATION', 'Creation'), ('MODIFICATION', 'Modification'), ('VERIFICATION', 'Verification')], db_column='NOTIFICATION_TYPE', max_length=50)),
            ],
            options={
                'db_table': 'NOTIFICATION_TYPE',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_frequency',
            field=models.ForeignKey(db_column='ID_NOTIFICATION_FREQUENCY', on_delete=django.db.models.deletion.DO_NOTHING, to='notifications.NotificationFrequency'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(db_column='ID_NOTIFICATION_TYPE', on_delete=django.db.models.deletion.DO_NOTHING, to='notifications.NotificationType'),
        ),
    ]
