# Generated by Django 2.1.11 on 2020-07-09 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEmailField',
            fields=[
                ('id', models.AutoField(db_column='ID_NOTIFICATION_EMAIL_FIELDS', primary_key=True, serialize=False)),
                ('email_field', models.EmailField(db_column='EMAIL_FIELD', max_length=200)),
                ('notification', models.ForeignKey(db_column='ID_NOTIFICATION', on_delete=django.db.models.deletion.CASCADE, related_name='email_fields', to='notifications.Notification')),
            ],
            options={
                'db_table': 'NOTIFICATION_EMAIL_FIELD',
                'managed': True,
            },
        ),
    ]
