# Generated by Django 2.1.11 on 2020-08-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationemailfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmPME',
            fields=[
                ('id', models.AutoField(db_column='ID_ALARMS_PME', primary_key=True, serialize=False)),
                ('utc_alarm_date', models.DateTimeField(db_column='UTC_ALARM_DATE')),
                ('utc_creation', models.DateTimeField(db_column='UTC_CREATION')),
                ('status', models.BooleanField(db_column='STATUS')),
            ],
            options={
                'db_table': 'ALARMS_PME',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlarmTypePME',
            fields=[
                ('id', models.AutoField(db_column='ID_ALARMS_TYPE', primary_key=True, serialize=False)),
                ('name_alarms_type', models.CharField(choices=[(1, 'Comunicação de dispositivos'), (2, 'Limite superior'), (3, 'Limite inferior'), (4, 'Qualidade de energia')], db_column='NAME_ALARMS_TYPE', max_length=50)),
            ],
            options={
                'db_table': 'ALARMS_TYPE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventTypePME',
            fields=[
                ('id', models.AutoField(db_column='ID_EVENT_TYPE', primary_key=True, serialize=False)),
                ('name_event_type', models.CharField(choices=[(1, 'Sag'), (2, 'Swell'), (3, 'Transient'), (4, 'Interruption'), (5, 'Communication'), (6, 'Demand'), (7, 'Energy'), (8, 'Voltage')], db_column='NAME_EVENT_TYPE', max_length=50)),
            ],
            options={
                'db_table': 'EVENT_TYPE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.AutoField(db_column='ID_NOTIFICATION_HISTORY', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'NOTIFICATION_HISTORY',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notificationemailfield',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notificationeventhistory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notificationfrequency',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notificationtargetemail',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notificationtype',
            options={'managed': False},
        ),
    ]
